// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function add(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

function first() {
  return Pervasives.failwith("For you to implement");
}

function second() {
  return Pervasives.failwith("For you to implement");
}

exports.add = add;
exports.first = first;
exports.second = second;
/*  Not a pure module */
