// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function range(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

exports.range = range;
/* No side effect */
