// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function advance_color() {
  return Pervasives.failwith("For you to implement");
}

exports.advance_color = advance_color;
/* No side effect */
