// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function non_zero() {
  return Pervasives.failwith("For you to implement");
}

exports.non_zero = non_zero;
/* No side effect */
