// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_primitive = require("bs-platform/lib/js/caml_primitive.js");

function largest(xs) {
  if (xs) {
    return Caml_primitive.caml_int_max(xs[0], largest(xs[1]));
  } else {
    return Pervasives.min_int;
  }
}

function smallest() {
  return Pervasives.failwith("For you to implement");
}

exports.largest = largest;
exports.smallest = smallest;
/* No side effect */
