// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var x = 0;

x = x + 1 | 0;

function min_and_max() {
  return Pervasives.failwith("For you to implement");
}

exports.min_and_max = min_and_max;
/*  Not a pure module */
