// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function plus(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

function times(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

function minus(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

function divide(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

exports.plus = plus;
exports.times = times;
exports.minus = minus;
exports.divide = divide;
/* No side effect */
