// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function card_value_to_score() {
  return Pervasives.failwith("For you to implement");
}

exports.card_value_to_score = card_value_to_score;
/* No side effect */
