// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function int_average(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

function float_average(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

var full_name = "Fred Flintstone";

console.log("Hi, My name is ");

console.log(full_name);

console.log(" and I am 5 years old");

exports.int_average = int_average;
exports.float_average = float_average;
/*  Not a pure module */
