// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function add1() {
  return Pervasives.failwith("For you to implement");
}

function square() {
  return Pervasives.failwith("For you to implement");
}

function twice(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

var add2 = Pervasives.failwith("For you to implement");

var raise_to_the_fourth = Pervasives.failwith("For you to implement");

exports.add1 = add1;
exports.square = square;
exports.twice = twice;
exports.add2 = add2;
exports.raise_to_the_fourth = raise_to_the_fourth;
/* add2 Not a pure module */
