// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var my_ints = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

function my_new_ints() {
  return Pervasives.failwith("For you to implement");
}

function sum_of_my_ints(ints) {
  return List.fold_left((function (total, my_int) {
                return total + my_int | 0;
              }), 0, ints);
}

if (sum_of_my_ints(my_ints) !== 15) {
  throw [
        Caml_builtin_exceptions.assert_failure,
        [
          "listOperations.re",
          79,
          9
        ]
      ];
}

function num_even_ints() {
  return Pervasives.failwith("For you to implement");
}

function first_num_greater_than_3(ints) {
  return List.find((function (x) {
                return +(x > 3);
              }), ints);
}

if (first_num_greater_than_3(my_ints) !== 4) {
  throw [
        Caml_builtin_exceptions.assert_failure,
        [
          "listOperations.re",
          94,
          9
        ]
      ];
}

exports.my_new_ints = my_new_ints;
exports.num_even_ints = num_even_ints;
/*  Not a pure module */
