// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function simpler_sum() {
  return Pervasives.failwith("For you to implement");
}

function simpler_product() {
  return Pervasives.failwith("For you to implement");
}

exports.simpler_sum = simpler_sum;
exports.simpler_product = simpler_product;
/* No side effect */
