// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function apply_if_nonzero(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

exports.apply_if_nonzero = apply_if_nonzero;
/* No side effect */
