// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function sum() {
  return Pervasives.failwith("For you to implement");
}

exports.sum = sum;
/* No side effect */
