// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function safe_divide(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

exports.safe_divide = safe_divide;
/* No side effect */
