// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function add_one_to_age(person) {
  return /* record */[
          /* age */person[/* age */0] + 1 | 0,
          /* first_name */person[/* first_name */1],
          /* last_name */person[/* last_name */2],
          /* number_of_cars */person[/* number_of_cars */3]
        ];
}

if (23 !== add_one_to_age(/* record */[
          /* age */22,
          /* first_name */"Cotton-eyed",
          /* last_name */"Joe",
          /* number_of_cars */0
        ])[/* age */0]) {
  throw [
        Caml_builtin_exceptions.assert_failure,
        [
          "records.re",
          52,
          9
        ]
      ];
}

function modify_person() {
  return Pervasives.failwith("For you to implement");
}

exports.modify_person = modify_person;
/*  Not a pure module */
