// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function map(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

function iter(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

function filter(_, _$1) {
  return Pervasives.failwith("For you to implement");
}

var My_list = /* module */[
  /* map */map,
  /* iter */iter,
  /* filter */filter
];

var numbers = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

exports.numbers = numbers;
exports.My_list = My_list;
/* No side effect */
